name: Build Cloud & Deploy Local

on:
  push:
    branches:
      - main

jobs:
  # Job 1: 在 GitHub 官方服务器上构建
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4 # 顺手升级到 v4 (建议)

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          extended: true

      - name: Build
        run: hugo --minify --environment china

      - name: Upload Artifact
        uses: actions/upload-artifact@v6
        with:
          name: public-site
          path: public/
          retention-days: 1

  # Job 2: 你的国内服务器把包拉下来部署
  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v7
        with:
          name: public-site
          path: temp_public/

      - name: Deploy to Nginx
        run: |
          # 这里的 /var/www/html/ 务必换成你实际的 Nginx 站点目录
          # rsync 会把 temp_public 下面的内容同步过去
          rsync -av --delete temp_public/ /opt/hugo-site-notes
          
          # 部署完清理临时文件
          rm -rf temp_public/
          
          echo "部署完成！"